# Generated by Django 4.2.5 on 2023-09-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
    ]
